### ISSUE TITLE
ConvAI2 data contains empty .txt files

### ISSUE THREAD

**Issue by nolanrbrady** [Chenrj233/LMEDR#7]
Hi,
I apologize if this is an ignorant question but I was trying to run your model and the execution failed with the error message:
```
Traceback (most recent call last):
  File "train_PersonaChat.py", line 135, in <module>
    persona, query, response, cand = create_data(f"data/ConvAI2/train_self{data_from}.txt")
  File "/Users/nolanbrady/Desktop/LMEDR/build_data_PersonaChat.py", line 67, in create_data
    assert len(query) == len(response) == len(persona) == len(cand)
AssertionError
```
After looking into it for a bit I think it's an issue with the way the training data is read into the model. When I looked at the files it looked like both `train_self_original.txt` and `train_self_revised.txt` were empty files. Is there a way to access the data that was used for this model originally or will we have to provide our own data?

Thank you for the help!

**Comment by Chenrj233** [comment]
Thank you for your question. The corresponding dataset can be obtained by the link in the Dataset column in README.
